This is the first part of our cooling system, the Heat Sink! #expression:neutral
It's responsible for seeping the heat generated by the CPU away into large metal pieces, that are then cooled down by fans.
There is another type of cooling, called "water powered cooling", but it is difficult to maintain, expensive, and overkill for most computers. It's mainly used for high end gaming rigs.
To install the heat sink, first, apply a special paste called "thermal paste" to the CPU. This paste helps transfer heat more efficiently.
Only a small amount of paste is needed! Be careful not to use too much or it'll just make a mess! #expression:error
Then, the Heat Sink itself is screwed on top of the CPU. Let's give it a try now! #expression:neutral